### ISSUE TITLE
recognition  of 4-digits captcha

### ISSUE THREAD

**Issue by clippit** [clippit/p-NJU#2]
neet to be updated to adapt the new captcha

**Comment by rdgt321** [comment]
I have just writen an algorithm to impl the recognition of 4-digits captcha.It uses 2 steps to deal with it.Because the captcha from p.nju.edu.cn is very clear and neat.So it just a simple dividing the captcha into 5 ares and convert the image to gray(use a specific threshold).After that,it calcls the sum of the point  and feature-cross-yline times in each area.it can simply mapping from pic-info to txt.
PS:I don't know if git can show java codes in here or not.:)
or I can send the example source code to you by RenRen or QQ:).

**Comment by clippit** [comment]
has been solved in v0.3 706b0ddc7d73a390c84189cf1d6c9d0ea8a5281e
